version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER=${MYSQL_USER}
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nestjs:
    build:
      dockerfile: Dockerfile
    image: nestjs
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    volumes:
      - .:/app

  react-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: react-app
    ports:
      - '5173:5173'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
