
POST {{base_url}}/suppliers
content-type: application/json

{
  "name": "J. Doe Supplier the Fourth",
  "address": "75 rue de Paris",
  "phone": "+336012345678",
  "email": "jdoe@supplier.com",
  "userId": 2
}